version: '3.8'

services:
  rag-service:
    build: .
    ports:
      - "8000:8000"
      - "11434:11434"
    volumes:
      - ./data:/app/data
      - ~/.ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
